# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-17 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q11', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q12', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q13', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q14', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q15', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q21', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q22', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q23', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q24', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q25', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q26', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q27', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q28', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q29', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q210', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q31', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q32', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Very low'), (3, 'Low'), (4, 'Moderate'), (5, 'High'), (7, 'Very High'), (8, 'Extreme')])),
                ('q33', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q34', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q35', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q36', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q37', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q38', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q39', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q310', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Somewhat Bad'), (4, 'Neither Good nor Bad'), (5, 'Somewhat Good'), (6, 'Good'), (7, 'Very Good')])),
                ('q311', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q312', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q313', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q314', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q315', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q316', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
                ('q317', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Somewhat Disagree'), (4, 'Neither Agree Nor Disagree'), (5, 'Somewhat Agree'), (6, 'Agree'), (7, 'Strongly Agree')])),
            ],
        ),
    ]
