# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='VGI.Unit'),
            preserve_default=False,
        ),
    ]
