# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-20 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates is the user admin.'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_citizen',
            field=models.BooleanField(default=False, help_text='Designates is the user citizen.'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Designates is the user expert.'),
        ),
    ]
