# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 18:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32639),
        ),
        migrations.AlterField(
            model_name='unit',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32639),
        ),
    ]
