# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0002_auto_20181023_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
