# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0003_auto_20181023_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
