# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0004_criteria_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='date',
        ),
    ]
