# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0005_remove_criteria_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
