# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 23:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VGI', '0007_auto_20181024_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=32639),
        ),
    ]
